# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import convert_pb2 as convert__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in convert_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConverterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConvertPdfToWord = channel.unary_unary(
                '/ConverterService/ConvertPdfToWord',
                request_serializer=convert__pb2.PdfFile.SerializeToString,
                response_deserializer=convert__pb2.WordFile.FromString,
                _registered_method=True)


class ConverterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConvertPdfToWord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConverterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConvertPdfToWord': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertPdfToWord,
                    request_deserializer=convert__pb2.PdfFile.FromString,
                    response_serializer=convert__pb2.WordFile.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ConverterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ConverterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConverterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConvertPdfToWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ConverterService/ConvertPdfToWord',
            convert__pb2.PdfFile.SerializeToString,
            convert__pb2.WordFile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
